JavaMain.class: JavaMain.java Ammo.class GameLabel.class Keyboard.class MassAmmo.class Scene.class Slime.class SlimeMob.class Snake.class Sound.class Sprite.class
    javac -g JavaMain.java

Ammo.class: Ammo.java
    javac -g Ammo.java

GameLabel.class: GameLabel.java
    javac -g GameLabel.java

Keyboard.class: Keyboard.java
    javac -g Keyboard.java

MassAmmo.class: MassAmmo.java
    javac -g MassAmmo.java

Scene.class: Scene.java
    javac -g Scene.java

Slime.class: Slime.java
    javac -g Slime.java

SlimeMob.class: SlimeMob.java
    javac -g SlimeMob.java

Snake.class: Snake.java
    javac -g Snake.java

Sound.class: Sound.java
    javac -g Sound.java

Sprite.class: Sprite.java
    javac -g Sprite.java

clean:
    rm *.class

run: JavaMain.class
    java JavaMain

